---
- name: Install Dependencies
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy artifact to home"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu    

- name: Creates Directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Uncompress Backend
  become: yes
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    
- name: Build
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- run start
    cd dist
    pm2 start main.js --update-env